# Generated by Django 2.2.6 on 2019-11-04 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='beginning',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='period',
            name='ending',
            field=models.DateField(unique=True),
        ),
    ]
