# Generated by Django 2.2.6 on 2019-11-09 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_budget', '0005_transaction_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='income',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='income', to='monthly_budget.Category'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='outcome',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outcome', to='monthly_budget.Category'),
        ),
    ]
