# Generated by Django 2.2.6 on 2019-11-19 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_budget', '0006_auto_20191109_0748'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_sum', models.DecimalField(decimal_places=2, max_digits=9)),
                ('income_sum', models.DecimalField(decimal_places=2, max_digits=9)),
                ('transferred_sum', models.DecimalField(decimal_places=2, max_digits=9)),
                ('spent_sum', models.DecimalField(decimal_places=2, max_digits=9)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='monthly_budget.Category')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='monthly_budget.Period')),
            ],
        ),
    ]
