# Generated by Django 2.2.6 on 2019-11-19 14:30

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_budget', '0007_balance'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='transaction',
            managers=[
                ('transactions', django.db.models.manager.Manager()),
            ],
        ),
    ]
