# Generated by Django 2.2.6 on 2019-11-19 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_budget', '0008_auto_20191119_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='code',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='default_planned_sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
            preserve_default=False,
        ),
    ]
