# Generated by Django 2.2.6 on 2019-11-22 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_budget', '0010_auto_20191119_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='code',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
