# Generated by Django 2.2.6 on 2019-11-30 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_budget', '0011_auto_20191122_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='income_sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='balance',
            name='planned_sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='balance',
            name='spent_sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='balance',
            name='transferred_sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
