# Generated by Django 2.2.6 on 2019-12-24 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_budget', '0012_auto_20191130_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
