# Generated by Django 2.2.6 on 2019-12-24 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_budget', '0013_balance_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balance',
            old_name='balance',
            new_name='balance_sum',
        ),
    ]
