# Generated by Django 2.2.6 on 2020-01-01 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_budget', '0014_auto_20191224_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balance',
            name='balance_sum',
        ),
    ]
