# Generated by Django 2.2.6 on 2020-01-01 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_budget', '0015_remove_balance_balance_sum'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Balance',
            new_name='Budget',
        ),
    ]
