# Generated by Django 2.2.6 on 2020-01-03 08:26

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_budget', '0016_auto_20200101_0809'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='period',
            managers=[
                ('periods', django.db.models.manager.Manager()),
            ],
        ),
    ]
