# Generated by Django 2.2.6 on 2020-01-04 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_budget', '0017_auto_20200103_0826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='code',
            new_name='category_code',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='sum',
            new_name='transaction_amount',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='date',
            new_name='transaction_date',
        ),
    ]
