# Generated by Django 2.2.6 on 2020-01-05 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_budget', '0020_auto_20200104_1640'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Plan',
            new_name='Balance',
        ),
    ]
