# Generated by Django 2.2.6 on 2020-01-06 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_budget', '0024_auto_20200105_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='chained_transaction',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='monthly_budget.Transaction'),
        ),
    ]
