# Generated by Django 3.0.6 on 2020-05-29 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_budget', '0028_auto_20200106_1617'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['category_code'], 'verbose_name_plural': 'categories'},
        ),
    ]
